apiVersion: v1
kind: Service
metadata:
  name: presidio-image-redactor
spec:
  type: {{ .Values.imageRedactor.service.type }}
  ports:
    - port: {{ .Values.imageRedactor.service.port }}
      targetPort: {{ .Values.imageRedactor.service.targetPort }}
  selector:
    app: presidio-image-redactor
