apiVersion: v1
kind: Service
metadata:
  name: presidio-analyzer
spec:
  type: {{ .Values.analyzer.service.type }}
  ports:
    - port: {{ .Values.analyzer.service.port }}
      targetPort: {{ .Values.analyzer.service.targetPort }}
  selector:
    app: presidio-analyzer
