apiVersion: v1
kind: Service
metadata:
  name: presidio-anonymizer
spec:
  type: {{ .Values.anonymizer.service.type }}
  ports:
    - port: {{ .Values.anonymizer.service.port }}
      targetPort: {{ .Values.anonymizer.service.targetPort }}
  selector:
    app: presidio-anonymizer
